# Generated by Django 2.2.12 on 2021-01-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.IntegerField(verbose_name='用户id'),
        ),
    ]
